#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vi'
export VISUAL='vi'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

if [[ "$(hostname)" == 'mbp.home.schunet.org' ]]; then
  export JAVA_HOME=`/usr/libexec/java_home`
  export AWS_AUTO_SCALING_HOME="/usr/local/src/AutoScaling-1.0.61.2"
fi

# Set the list of directories that Zsh searches for programs.
if [[ "$(hostname)" == 'mbp.home.schunet.org' ]]; then
   path=(
     /usr/local/{bin,sbin}
     $HOME/.rvm/bin
     /opt/bin
     /usr/local/mysql/bin
     $AWS_AUTO_SCALING_HOME/bin
     /usr/local/src/ec2-api-tools-1.6.7.4/bin
     $path
   )
else
   path=(
     /usr/local/{bin,sbin}
     $path
   )
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

if [[ "$(hostname)" == 'mbp.home.schunet.org' ]]; then
  source ~/.rvm/scripts/rvm
fi

